# Generated by Django 5.2.5 on 2025-09-01 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('tipo_evento', models.CharField(choices=[('conferencia', 'Conferencia'), ('taller', 'Taller'), ('capacitacion', 'Capacitación')], default='conferencia', max_length=20)),
                ('capacidad', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('F', 'Finalizado')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
