# Generated by Django 5.2.5 on 2025-09-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='capacidad',
        ),
        migrations.AddField(
            model_name='evento',
            name='capacidad_num',
            field=models.PositiveIntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('F', 'Finalizado')], default='A', max_length=1),
        ),
    ]
