# Generated by Django 5.2.6 on 2025-09-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_registroevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
