# Generated by Django 5.2.5 on 2025-09-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('organizador', 'Organizador'), ('estudiante', 'Estudiante')], default='estudiante', max_length=20),
        ),
    ]
